datashow_tcc/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),  
    path('accounts/', include('usuarios.urls')),
    path('reservas/', include('reservas.urls')),     
]

paginas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.Home,name='home')
]

reservas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.CreateReservaView.as_view(), name='reserva-create'),
    path('update/<int:pk>', views.UpdateReservasView.as_view(), name='reserva-update'),
    path('delete/<int:pk>', views.DeleteReservaView.as_view(), name='reserva-delete'),
    path('agendar/create', views.CreateAgendarProjetorView.as_view(), name='agendar-create'),
    path('agendar/update/<int:pk>', views.UpdateAgendarProjetorView.as_view(), name='agendar-update'),
    path('get_turmas/<int:curso_id>/',
         views.get_turmas_por_curso, name='get_turmas_por_curso'),
    path('get_horarios_disponiveis/<int:projetor_id>/<str:data>/',
         views.get_horarios_disponiveis, name='get_horarios_disponiveis'),
    path('tabela/',views.tabela_reserva,name='tabela_reserva'),
]

reservas/models.py
from django.db import models
from django.contrib.auth.models import User
from reservas import choices
from multiselectfield import MultiSelectField


class ProjetorModel(models.Model):
    nome = models.CharField(max_length=50)
    disponibilidade = models.BooleanField(
        default=False, verbose_name='disponível')

    def __str__(self):
        return f'{self.nome}'


class CursoModel(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.nome}'


class TurmaModel(models.Model):
    turma = models.IntegerField()
    curso = models.ForeignKey(CursoModel, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.turma} - {self.curso}'


class ReservaModel(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    curso = models.ForeignKey(CursoModel, on_delete=models.PROTECT)
    projetor = models.ForeignKey(ProjetorModel, on_delete=models.PROTECT)
    data = models.DateField()
    create_data = models.DateField(auto_now_add=True)
    horario = MultiSelectField(
        choices=choices.HORARIO_CHOICES, max_choices=9, max_length=50)
    turmas = models.ManyToManyField(TurmaModel)
    entregue = models.BooleanField(default=False, verbose_name='Projetor Entregue')
    devolucao = models.BooleanField(default=False, verbose_name='Projetor Devolvido')
    
    def marca_como_entregue(self):
        #Adicionar o código para marcar que o projetor foi entregue para o projetor.
        self.entregue = True
        self.save()
    
    def desmarca_como_entregue(self):
        #Adicionar o código para marcar que o projetor não foi entregue para o projetor.
        self.entregue = False
        self.save()
        
    def marca_como_devolvido(self):
        #Adicionar o código para marcar projetor como devolvido para gestao.
        self.devolucao = True
        self.save()
    
    def desmarca_como_devolvido(self):
        #Adicionar o código para marcar projetor como não devolvido para gestao.
        self.devolucao = False
        self.save()
        
    def __str__(self):
        return f'Usuario: {self.usuario} Projetor: {self.projetor} Data da reserva: {self.data} Criação da reserva: {self.create_data}'

reservas/forms.py
from django import forms
from . import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from reservas import choices
from datetime import datetime


class ReservaModelForm(forms.ModelForm):
    class Meta:
        model = models.ReservaModel
        fields = ['curso', 'horario', 'turmas', 'projetor','data',]
        widgets = {
            'turmas': forms.CheckboxSelectMultiple,
            'data':forms.DateInput(attrs={'type':'date'})
        }

    def clean_horario(self):
        horario_selecionado = self.cleaned_data.get('horario')

        if len(horario_selecionado) > 6:
            raise ValidationError(
                'Você só pode selecionar no máximo 6 horários.')
        return horario_selecionado

    def clean(self):
        cleaned_data = super().clean()
        turmas = cleaned_data.get('turmas')
        data = cleaned_data.get('data')
        horario = self.cleaned_data.get('horario')
        projetor = self.cleaned_data.get('projetor')

        if not turmas:
            raise ValidationError('Informe pelo menos uma turma')

        if not horario:
            raise ValidationError('Informe o Horário')
        
        if data.day > datetime.now().day:
            raise ValidationError('A data não pode ser maior que a data atual')
            
        if horario:
            horarios_desabilitados = [
                horario_choice[0] for horario_choice in choices.HORARIO_CHOICES if horario_choice[0] not in horario]
            for h in horario:
                if h in horarios_desabilitados:
                    raise ValidationError(
                        f'O horário {h} não está disponível para reserva.')

        id = self.instance.id if self.instance else None

        reservas = models.ReservaModel.objects.filter(
            projetor=projetor,
            data=data
        ).exclude(id=id)

        horarios_reservados = [h for r in reservas for h in r.horario]
        horarios_selecionados = horario

        if any(h in horarios_reservados for h in horarios_selecionados):
            raise ValidationError(
                "Este projetor já está reservado para o mesmo horário")


class AgendarProjetorForm(forms.ModelForm):
    class Meta:
        model = models.ReservaModel
        fields = ['curso', 'horario', 'turmas', 'projetor', 'data']
        widgets = {
            'turmas': forms.CheckboxSelectMultiple,
            'data': forms.DateInput(attrs={'type': 'date'}),
        }

    def clean_horario(self):
        horario_selecionado = self.cleaned_data.get('horario')

        if horario_selecionado and len(horario_selecionado) > 6:
            raise ValidationError(
                'Você só pode selecionar no máximo 6 horários.')
        return horario_selecionado

    def clean(self):
        cleaned_data = super().clean()
        data = cleaned_data.get('data')
        projetor = cleaned_data.get('projetor')
        horario = self.cleaned_data.get('horario')
        projetor = self.cleaned_data.get('projetor')

        if data and data == timezone.now().date():
            raise ValidationError('A data nao pode ser igual a data atual')

        if data and data < timezone.now().date():
            raise ValidationError(
                "A data não pode ser menor que a data atual.")

        if data and data.year > timezone.now().date().year:
            raise ValidationError(
                "A data não pode ser maior que o ano atual.")

        if data and data > timezone.now().date() + timezone.timedelta(days=2):
            raise ValidationError(
                'Você não pode reservar com mais de dois dias de antecedência')

        if not horario:
            raise ValidationError('Informe o Horário')
            
        if horario:
            horarios_desabilitados = [
                horario_choice[0] for horario_choice in choices.HORARIO_CHOICES if horario_choice[0] not in horario]
            for h in horario:
                if h in horarios_desabilitados:
                    raise ValidationError(
                        f'O horário {h} não está disponível para reserva.')

        id = self.instance.id if self.instance else None

        reservas = models.ReservaModel.objects.filter(
            projetor=projetor,
            data=data
        ).exclude(id=id)

        horarios_reservados = [h for r in reservas for h in r.horario]
        horarios_selecionados = horario

        if any(h in horarios_reservados for h in horarios_selecionados):
            raise ValidationError(
                "Este projetor já está reservado para o mesmo horário")

reservas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import View
from . import models
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from reservas import choices
from django.utils import timezone
from . import forms
from django.contrib.auth.decorators import login_required
from datetime import datetime


class CreateReservaView(LoginRequiredMixin, CreateView):
    template_name = 'form_reservar_create.html'
    form_class = forms.ReservaModelForm
    success_url = reverse_lazy('tabela_reserva')
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        form.instance.data = datetime.now()
        return super().form_valid(form)


class UpdateReservasView(LoginRequiredMixin, UpdateView):
    template_name = 'form_reservar_update.html'
    form_class = forms.ReservaModelForm
    success_url = reverse_lazy('tabela_reserva')
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        form.instance.data = datetime.now()

        # Verifica se a data do objeto é igual à data atual
        if form.instance.data == timezone.now().date():
            # Se sim, redireciona para outra página
            self.success_url = reverse_lazy('reserva-update')

        return super().form_valid(form)

    def get_object(self, queryset=None):
        obj = get_object_or_404(
            models.ReservaModel, pk=self.kwargs['pk'], usuario=self.request.user)

        self.initial = {'data': obj.data.strftime('%Y-%m-%d')}

        return obj

    def get(self, request, *args, **kwargs):
        reserva = self.get_object()
        if reserva.data >= timezone.now().date():
            return super().get(request, *args, **kwargs)
        else:
            raise Http404("Não é possível atualizar reservas passadas.")


class DeleteReservaView(LoginRequiredMixin, View):
    login_url = reverse_lazy('login')

    def get(self, request, pk):
        reserva = get_object_or_404(models.ReservaModel, pk=pk)

        if reserva.data >= timezone.now().date():
            form = forms.ReservaModelForm(instance=reserva, initial={
                                          'data': reserva.data.strftime('%Y-%m-%d')})
            template_name = 'form_reservar_delete.html'
            context = {'form': form, 'reserva': reserva}
            return render(request, template_name, context)
        else:
            raise Http404("Não é possível deletar reservas passadas.")

    def post(self, request, pk):
        reserva = get_object_or_404(models.ReservaModel, pk=pk)

        if request.method == 'POST':
            reserva.delete()
            return redirect('tabela_reserva')


class CreateAgendarProjetorView(LoginRequiredMixin, CreateView):
    template_name = 'form_agendar_create.html'
    form_class = forms.AgendarProjetorForm
    success_url = reverse_lazy('tabela_reserva')
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)


class UpdateAgendarProjetorView(LoginRequiredMixin, UpdateView):
    template_name = 'form_agendar_update.html'
    form_class = forms.AgendarProjetorForm
    success_url = reverse_lazy('tabela_reserva')
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)

    def get_object(self, queryset=None):
        obj = get_object_or_404(
            models.ReservaModel, pk=self.kwargs['pk'], usuario=self.request.user)

        self.initial = {'data': obj.data.strftime('%Y-%m-%d')}

        return obj

    def get(self, request, *args, **kwargs):
        reserva = self.get_object()
        if reserva.data >= timezone.now().date():
            return super().get(request, *args, **kwargs)
        else:
            raise Http404("Não é possível atualizar reservas passadas.")


@login_required(login_url="login")
def tabela_reserva(request):
    data_atual = timezone.now().date()
    reserva_model_atual = models.ReservaModel.objects.filter(
        usuario=request.user, data=data_atual)
    reserva_model_futuro = models.ReservaModel.objects.filter(
        usuario=request.user, data__gt=data_atual)
    hoje = timezone.now().date()
    reserva_model_all = models.ReservaModel.objects.filter(
        usuario=request.user).order_by('-data')
    return render(request, 'tabela_reservas.html', {'reservas': reserva_model_atual,
                                                    'reservas_futuras': reserva_model_futuro,
                                                    'reservas_all': reserva_model_all,
                                                    'hoje': hoje,
                                                    })


@login_required(login_url="login")
def get_turmas_por_curso(request, curso_id):
    curso = get_object_or_404(models.CursoModel, id=curso_id)
    turmas = models.TurmaModel.objects.filter(curso=curso)

    turmas_data = [{'id': turma.id, 'turma': turma.turma} for turma in turmas]

    return JsonResponse(turmas_data, safe=False)


@login_required(login_url="login")
def get_horarios_disponiveis(request, projetor_id, data):
    reservas = models.ReservaModel.objects.filter(
        projetor_id=projetor_id, data=data)
    horarios_reservados = set()
    for reserva in reservas:
        horarios_reservados.update(reserva.horario)

    horarios_disponiveis = [
        horario for horario in choices.HORARIO_CHOICES if horario[0] not in horarios_reservados]

    return JsonResponse({'horarios': horarios_disponiveis})

reservas/templates/form_agendar_create.html
{% extends "base.html" %}
{% load static %}
{% block title%}
<title>Agendar Reservas</title>
{% endblock %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/forms_reservas.css' %}">
{% endblock %}
{% block content %}
<form method="post" class="reservation-form">
    <h1 id="title-form">Agendar Reservar</h1>
    {% csrf_token %}
    <div class="form-group">
        {{ form.projetor.label_tag }}
        {{ form.projetor }}
    </div>
    <div class="form-group">
        {{ form.curso.label_tag }}
        {{ form.curso }}
    </div>
    <div class="form-group">
        <label for="id_turmas">Turmas:</label>
        <div id="id_turmas_container">
            <!-- Aqui as turmas relacionadas ao curso serão inseridas via JavaScript -->
        </div>
    </div>
    <div class="form-group">
        {{ form.data.label_tag }}
        {{ form.data }}
    </div>
    <div class="form-group" id="form-horario">
        {{ form.horario.label_tag }}
        {{ form.horario }}
    </div>
    {% if form.non_field_errors %}
    <div id="error-message">{{ form.non_field_errors }}</div>
    {% endif %}
    {% if form.horario.errors %}
    <div id="error-message">{{ form.horario.errors }}</div>
    {% endif %}
    <button type="submit" class="submit-button">Agendar</button>
</form>
<input type="hidden" id="current_user" value="{{ request.user.username }}">
{% endblock %}
{% block script %}
<script src="{% static 'js/select_materias_por_curso.js' %}"></script>
<script src="{% static 'js/select_turmas_por_curso.js' %}"></script>
<script src="{% static 'js/select_horarios_disponiveis.js' %}"></script>
{% endblock %}

reservas/templates/form_agendar_update.html
{% extends "base.html" %}
{% load static %}
{% block title%}
<title>Agendar Reservas</title>
{% endblock %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/forms_reservas.css' %}">
{% endblock %}
{% block content %}
<form method="post" class="reservation-form">
    <h1 id="title-form">Agendar Reservar</h1>
    {% csrf_token %}
    <div class="form-group">
        {{ form.projetor.label_tag }}
        {{ form.projetor }}
    </div>
    <div class="form-group">
        {{ form.curso.label_tag }}
        {{ form.curso }}
    </div>
    <div class="form-group">
        <label for="id_turmas">Turmas:</label>
        <div id="id_turmas_container">
            <!-- Aqui as turmas relacionadas ao curso serão inseridas via JavaScript -->
        </div>
    </div>
    <div class="form-group">
        {{ form.data.label_tag }}
        {{ form.data }}
    </div>
    <div class="form-group" id="form-horario">
        {{ form.horario.label_tag }}
        {{ form.horario }}
    </div>
    {% if form.non_field_errors %}
    <div id="error-message">{{ form.non_field_errors }}</div>
    {% endif %}
    <button type="submit" class="submit-button">Agendar</button>
</form>
<input type="hidden" id="current_user" value="{{ request.user.username }}">
{% endblock %}
{% block script %}
<script src="{% static 'js/select_materias_por_curso.js' %}"></script>
<script src="{% static 'js/select_turmas_por_curso.js' %}"></script>
{% endblock %}

reservas/templates/form_reservar_create.html
{% extends "base.html" %}
{% load static %}
{% block title%}
<title>Reservar</title>
{% endblock %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/forms_reservas.css' %}">
{% endblock %}
{% block content %}


<form method="post" id="reservation-form">
    {% csrf_token %}
    <h1 id="title-form">Reservar para hoje</h1>
    <h3 id="mensagem-horario"></h3>


    <div class="form-group">
        {{ form.projetor.label_tag }}
        {{ form.projetor }}
    </div>
    <div class="form-group">
        {{ form.curso.label_tag }}
        {{ form.curso }}
    </div>
    <div class="form-group">
        <label for="id_turmas">Turmas:</label>
        <div id="id_turmas_container">
            <!-- Aqui as turmas relacionadas ao curso serão inseridas via JavaScript -->
        </div>
    </div>
    <div class="form-group">
        {{ form.data.label_tag }}
        {{ form.data }}
    </div>
    <div class="form-group" id="form-horario">
        {{ form.horario.label_tag }}
        {{ form.horario }}
    </div>
    {% if form.non_field_errors %}
    <div id="error-message">{{ form.non_field_errors }}</div>
    {% endif %}
    <button type="submit" class="submit-button">Reservar</button>
</form>
<input type="hidden" id="current_user" value="{{ request.user.username }}">
{% endblock %}
{% block script %}
<script src="{% static 'js/select_materias_por_curso.js' %}"></script>
<script src="{% static 'js/select_turmas_por_curso.js' %}"></script>
<script src="{% static 'js/desabilitar_horarios_passados.js' %}"></script>
<script src="{% static 'js/mensagem_horario_disponivel.js' %}"></script>
<script src="{% static 'js/select_horarios_disponiveis.js' %}"></script>
{% endblock %}

reservas/templates/form_reservar_delete.html
{% extends "base.html" %}
{% load static %}
{% block title%}
<title>Deletar Reservas</title>
{% endblock %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/forms_reservas.css' %}">
{% endblock %}
{% block content %}


<form method="post" class="reservation-form">
    {% csrf_token %}
    <h1 id="title-form">Reservar para hoje</h1>

    <div class="form-group">
        {{ form.projetor.label_tag }}
        {{ form.projetor }}
    </div>
    <div class="form-group">
        {{ form.curso.label_tag }}
        {{ form.curso }}
    </div>
    <div class="form-group">
        <label for="id_turmas">Turmas:</label>
        <div id="id_turmas_container">
            <!-- Aqui as turmas relacionadas ao curso serão inseridas via JavaScript -->
        </div>
    </div>
    <div class="form-group" id="form-horario">
        {{ form.horario.label_tag }}
        {{ form.horario }}
    </div>
    {% if form.non_field_errors %}
    <div id="error-message">{{ form.non_field_errors }}</div>
    {% endif %}
    <button type="submit" class="submit-button" id="submit-button-delete">Deletar</button>
</form>
<input type="hidden" id="current_user" value="{{ request.user.username }}">
{% endblock %}
{% block script %}
<script src="{% static 'js/select_materias_por_curso.js' %}"></script>
<script src="{% static 'js/select_turmas_por_curso.js' %}"></script>
<script src="{% static 'js/desabilitar_horarios_passados.js' %}"></script>
{% endblock %}

reservas/templates/form_reservar_update.html
{% extends "base.html" %}
{% load static %}
{% block title%}
<title>Atualizar Reserva</title>
{% endblock %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/forms_reservas.css' %}">
{% endblock %}
{% block content %}
<form method="post" class="reservation-form">
    <h1 id="title-form">Agendar Reservar</h1>
    {% csrf_token %}
    <div class="form-group">
        {{ form.projetor.label_tag }}
        {{ form.projetor }}
    </div>
    <div class="form-group">
        {{ form.curso.label_tag }}
        {{ form.curso }}
    </div>
    <div class="form-group">
        <label for="id_turmas">Turmas:</label>
        <div id="id_turmas_container">
            <!-- Aqui as turmas relacionadas ao curso serão inseridas via JavaScript -->
        </div>
    </div>
    <div class="form-group">
        {{ form.data.label_tag }}
        {{ form.data }}
    </div>
    <div class="form-group" id="form-horario">
        {{ form.horario.label_tag }}
        {{ form.horario }}
    </div>
    {% if form.non_field_errors %}
    <div id="error-message">{{ form.non_field_errors }}</div>
    {% endif %}
    <button type="submit" class="submit-button">Agendar</button>
</form>
<input type="hidden" id="current_user" value="{{ request.user.username }}">
{% endblock %}
{% block script %}
<script src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
<script src="{% static 'js/select_materias_por_curso.js' %}"></script>
<script src="{% static 'js/select_turmas_por_curso.js' %}"></script>
<script src="{% static 'js/desabilitar_horarios_passados.js' %}"></script>
{% endblock %}

reservas/templates/tabela_reservas.html
{% extends "base.html" %}
{% load static %}
{% block title%}
<title>Tabela Reservas</title>
{% endblock %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/tabela_reservas.css' %}">
{% endblock %}
{% block content %}
<div class="reservas-table-container">
    <!-- Tabela 1: Reservas para hoje -->
    <table class="reservas-table">
        <caption>Reservas para hoje</caption>
        <tr>
            <th>Projetor</th>
            <th>Data</th>
            <th>Turma</th>
            <th>Ações</th>
        </tr>
        {% for reserva in reservas %}
        <tr>
            <td>{{ reserva.projetor }}</td>
            <td>{{ reserva.data }}</td>
            <td>{% for turma in reserva.turmas.all %}
                {{ turma }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
            <td>
                {% if reserva.data == hoje %}
                <a href="{% url 'reserva-update' reserva.pk %}" id="edit-icon"><i class="fas fa-edit"></i></a>
                {% else %}
                <a href="{% url 'agendar-update' reserva.pk %}" id="edit-icon"><i class="fas fa-edit"></i></a>
                {% endif %}
                <a href="{% url 'reserva-delete' reserva.pk %}" id="trash-icon"><i class="fas fa-trash"></i></a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">Nenhuma reserva para hoje.</td>
        </tr>
        {% endfor %}
    </table>

    <!-- Tabela 2: Reservas Futuras -->
    <table class="reservas-table">
        <caption>Reservas Futuras</caption>
        <tr>
            <th>Projetor</th>
            <th>Data</th>
            <th>Turma</th>
            <th>Ações</th>
        </tr>
        {% for reserva in reservas_futuras %}
        <tr>
            <td>{{ reserva.projetor }}</td>
            <td>{{ reserva.data }}</td>
            <td>{% for turma in reserva.turmas.all %}
                {{ turma }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
            <td>
                {% if reserva.data == hoje %}
                <a href="{% url 'reserva-update' reserva.pk %}" id="edit-icon"><i class="fas fa-edit"></i></a>
                {% else %}
                <a href="{% url 'agendar-update' reserva.pk %}" id="edit-icon"><i class="fas fa-edit"></i></a>
                {% endif %}
                <a href="{% url 'reserva-delete' reserva.pk %}" id="trash-icon"><i class="fas fa-trash"></i></a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">Nenhuma reserva futura encontrada.</td>
        </tr>
        {% endfor %}
    </table>

    <!-- Tabela 3: Todas as Reservas -->
    <table class="reservas-table">
        <caption>Todas as Reservas</caption>
        <tr>
            <th>Projetor</th>
            <th>Data</th>
            <th>Turma</th>
        </tr>
        {% for reserva in reservas_all %}
        <tr>
            <td>{{ reserva.projetor }}</td>
            <td>{{ reserva.data }}</td>
            <td>{% for turma in reserva.turmas.all %}
                {{ turma }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">Nenhuma reserva encontrada.</td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}